### ISSUE TITLE
Save and restore preferences

### ISSUE THREAD

**Issue by travisspencer** [curityio/oauthtest#4]
The server's base URL, authorize and token endpoints should be persisted and restored across app starts. Also, if there are no preferred values, then some sensible defaults should be used rather than nothing.

**Comment by travisspencer** [comment]
I started this in 6ecb20305d28c9aa91ef04b268c98c56048ad8d0. The things I'm unsure about are:
- Is what I did in that commit inline with the architectural ideas of the app?
- How do you get the newest values of the preferences on app shutdown? I added a `setOnCloseRequest` event handler on the main stage. That fires, but the values are the ones before the user changes them, so their preferences aren't getting saved. It might just be silly mistake where I'm passing the initial values into the closure, as the values are indeed persisted.
- Why do the preferences for the OAuth server show up on the SSL settings page? Couldn't figure that one out.

@renatoathaydes, can you comment?

**Comment by renatoathaydes** [comment]
- Is what I did in that commit inline with the architectural ideas of the app?

Yes, exactly what I would have done.
- How do you get the newest values of the preferences on app shutdown? I added a setOnCloseRequest event handler on the main stage. That fires, but the values are the ones before the user changes them, so their preferences aren't getting saved. It might just be silly mistake where I'm passing the initial values into the closure, as the values are indeed persisted.

I am using Events to handle this... you should use the `EventBus` to listen for changes in the state of the server. Save that state in a field, then on shutdown, persist the latest state.

Make the field volatile, because it will be set in the JavaFX Thread, but will be read in the shutdown Thread. It's ok because the state classes (all Events) are final, so they can be shared between Threads.
- Why do the preferences for the OAuth server show up on the SSL settings page? Couldn't figure that one out.

Do you mean the SSL keystore, password etc? Those are supposed to be SSL for the HTTP client :) If that's not what you mean, you probably got some code I was refactoring or something... I will push lots of more changes soon... I don't think there's such problem now.

**Comment by renatoathaydes** [comment]
I've added a "card" in the "Projects" tab of this GitHub repo... it's like JIRA for GitHub. Check it out!

We should add the tasks we're working on there to avoid conflicts... I almost implemented the same thing you're doing now, but by luck started working on something else instead.
